---
  - name: Install Epel Repository
    yum: name=epel-release state=latest
    
  - name: Install Redis
    yum: name=redis state=latest

  - name: Start Redis
    service: name=redis state=started enabled=yes

  - name: Copy config
    template: src=redis.conf.j2 dest=/etc/redis.conf
    notify: restart redis
