---
# Elasticsearch Ansible Variables

elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_version: 2.1.1
elasticsearch_yum_dependencies:
  - htop
  - unzip
  - epel-release
elasticsearch_max_open_files: 65535
elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_plugin_dir: /usr/share/elasticsearch/plugins
elasticsearch_log_dir: /var/log/elasticsearch
elasticsearch_data_dir: /var/lib/elasticsearch
elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch
elasticsearch_pid_dir: /var/run
elasticsearch_service_startonboot: yes
elasticsearch_timezone: "America/Chicago"

#elasticsearch_http_cors_enabled: "false"
elasticsearch_service_state: started
