---
  - name: install epel
    yum: name=epel-release state=latest

  - name: install nginx
    yum: name=nginx state=latest

  - name: start nginx
    service: name=nginx state=started enabled=yes

  - name: copy nginx config
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: copy kibana vhost config
    copy: src=kibana.conf dest=/etc/nginx/conf.d/kibana.conf
    notify: restart nginx
