---

- name: elastic-install | Install dependencies
  yum:
    pkg={{ item }}
    state=present
  with_items: elasticsearch_yum_dependencies

- name: elastic-install | Configuring elastic group
  group:
    name={{ elasticsearch_group }}

- name: elastic-install | Configuring elastic user
  user:
    name={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    createhome=no

- name: elastic-install | Ensure temp elasticsearch directories exists
  file:
    path="{{ elasticsearch_work_dir }}"
    state=directory
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    recurse=yes

- name: elastic-install | Check if we have elastic with same version installed
  stat: path="/usr/share/elasticsearch/lib/elasticsearch-{{ elasticsearch_version }}.jar"
  register: installed_version

- debug: var=installed_version

- name: elastic-install | Try to stop elasticsearch if running
  service:
    name=elasticsearch
    state=stopped
  ignore_errors: yes
  when: not installed_version.stat.exists

- name: install gpg key for repository
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: install elasticsearch repository
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: elastic-install | Uninstalling previous version if applicable
  yum:
     name="elasticsearch"
     state="absent"
  when: not installed_version.stat.exists

- name: elastic-install | Remove elasticsearch directory
  file:
    path="{{ elasticsearch_home_dir }}"
    state=absent
  when: not installed_version.stat.exists

- name: install elasticsearch
  yum: name=elasticsearch state=latest

- name: elastic-install | Ensure elastic directories exists
  file:
    path="{{ item }}"
    state=directory
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    recurse=yes
  with_items:
     - "{{ elasticsearch_work_dir }}"
     - "{{ elasticsearch_home_dir }}"
     - "{{ elasticsearch_log_dir }}"
     - "{{ elasticsearch_data_dir }}"
     - "{{ elasticsearch_work_dir }}"
     - "{{ elasticsearch_conf_dir }}"

- name: Configure limits max_open_files
  lineinfile:
    dest=/etc/security/limits.conf
    regexp='^{{ elasticsearch_user }}     -    nofile    {{ elasticsearch_max_open_files }}'
    insertafter=EOF
    line='{{ elasticsearch_user }}     -    nofile    {{ elasticsearch_max_open_files }}'
  when: elasticsearch_max_open_files is defined
  notify: Restart Elasticsearch

- name: elastic-install | Configure limits max_locked_memory
  lineinfile:
    dest=/etc/security/limits.conf
    regexp='^{{ elasticsearch_user }}     -    memlock   {{ elasticsearch_max_locked_memory }}'
    insertafter=EOF
    line='{{ elasticsearch_user }} soft memlock {{ elasticsearch_max_locked_memory }}'
  when: elasticsearch_max_locked_memory is defined
  notify: Restart Elasticsearch

- name: elastic-install | Configure limits max_locked_memory
  lineinfile:
    dest=/etc/security/limits.conf
    regexp='^{{ elasticsearch_user }}     -    memlock   {{ elasticsearch_max_locked_memory }}'
    insertafter=EOF
    line='{{ elasticsearch_user }} hard memlock {{ elasticsearch_max_locked_memory }}'
  when: elasticsearch_max_locked_memory is defined
  notify: Restart Elasticsearch

- name: elastic-install | Configuring Elasticsearch elasticsearch.yml Node
  template:
    src=elasticsearch.yml.j2
    dest={{ elasticsearch_conf_dir }}/elasticsearch.yml
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    mode=0644
  when: elasticsearch_conf_dir is defined
  notify: Restart Elasticsearch

- name : elastic-install | Configure /etc/default/elasticsearch
  template:
    src=elasticsearch.default.j2
    dest=/etc/default/elasticsearch
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    mode=0644
  notify: Restart Elasticsearch
