---
# Host to input multiple beats and output to Redis
  - hosts: logstash-queue
    roles:
      - openjdk
      - logstash

    vars:
      logstash_inputs: |
       syslog { host => "{{ ansible_enp0s8.ipv4.address }}"
                port => "514"
                type => "syslog_input"
              }

       syslog { host => "{{ ansible_enp0s8.ipv4.address }}"
                port => "515"
                type => "syslog_input_local"
              }

      logstash_filters: |
       geoip { source => "ip_address"
             }

       multiline { pattern => "^No lfn2pfn"
                   what => "previous"
                 }

      logstash_outputs: |
       file { path => "/var/log/logstash/output.log"
            }

# Host to take input from Redis and feed to Elasticsearch
  - hosts: logstash
    roles:
      - openjdk
      - logstash

    vars:
      logstash_inputs: |

      logstash_filters: |

      logstash_outputs: |
