---
# Host to input multiple beats and output to Redis
  - hosts: logstash-queue
    roles:
      - openjdk
      - logstash

    vars:
      logstash_inputs: |
       beats {
              port => 5044
             }

      logstash_filters: |
       grok {
              type => "apache=access"
              match => [ "message", "%{COMBINEDAPACHELOG}" ]
            }

       grok {
             type => "nginx-access"
             match => [ "message", "%{COMBINEDAPACHELOG}" ]
            }

      logstash_outputs: |
       redis {
               host => "172.16.81.6"
               data_type => "list"
               key => "logstash"
             }

# Host to take input from Redis and feed to Elasticsearch
  - hosts: logstash
    roles:
      - openjdk
      - logstash

    vars:
      logstash_inputs: |
       redis {
              host => "172.16.81.6"
              type => "redis-input"
              data_type => "list"
              key => "logstash"
             }

      logstash_filters: |
       date {
              type => "apache-access"
              match => [ "message", "%{COMBINEDAPACHELOG}" ]
            }

      logstash_outputs: |
       elasticsearch {
                      hosts => ["172.16.81.8"]
                     }
