---

  - name: remove kibana archive
    file: path=/tmp/kibana-{{kibana_full_version}}.tgz state=absent force=yes

  - name: reload systemd
    shell: systemctl daemon-reload
    changed_when: false
    when: "kibana_manage_service"

  - name: restart kibana
    service: name=kibana state=restarted

  - name: restart nginx
    service: name=nginx state=restarted
